const PLANTS = [
    {
        no: '01',
        name: '大花咸豐草',
        img: 'plants/img/IMG_NO01.png',
        type: '草本植物',
        genus: '菊科鬼針草屬',
        title: '毫不起眼 卻暗藏威脅 隱身於都市中...',
        character:
            '白色的花瓣與黃色的花蕊是最大特徵，果實具有倒鉤，容易附著於衣物或毛皮上，散布生長',
        desc: '來自美洲，依靠強大的繁殖力即可附著的種子，成為最常見的外來種',
    },
    {
        no: '02',
        name: '非洲鳳仙花',
        img: 'plants/img/IMG_NO02.png',
        type: '草本植物',
        genus: '鳳仙花科鳳仙花屬',
        title: '鳳凰般美麗又具生命力 卻也讓其他植物黯淡...',
        desc: '來自非洲，觀賞植物，有排他性，常被選為造景植物，導致族群大量生長',
    },
    {
        no: '03',
        name: '巴西水竹草',
        img: 'plants/img/IMG_NO03.png',
        type: '草本植物',
        genus: '鴨跖草科水竹草屬',
        title: '不斷 不斷的復生 覆蓋大地的災害...',
        desc: '來自南美洲，看似弱小，卻有著強韌的生命力，即使斷掉也能重生',
    },
    {
        no: '04',
        name: '小花蔓澤蘭',
        img: 'plants/img/IMG_NO04.png',
        type: '攀爬植物',
        genus: '菊科蔓澤蘭屬',
        title: '所到之處 寸草不生 有著「綠癌」的稱號...',
        desc: '來自中南美洲，最危險的入侵者，會盤繞在大樹上，並將他們殺死，造成生態浩劫',
    },
    {
        no: '05',
        name: '水芙蓉',
        img: 'plants/img/IMG_NO05.png',
        type: '水生植物',
        genus: '天南星科大薸屬',
        title: '漂浮在水面上 但在水中隱藏什麼...',
        desc: '來自美洲，依靠快速的繁殖力，佔據了水面，遮擋了陽光，使水中生物死亡',
    },
    {
        no: '06',
        name: '布袋蓮',
        img: 'plants/img/IMG_NO06.png',
        type: '水生植物',
        genus: '雨久花科梭魚草屬',
        title: '原本只有一朵花 不知不覺佔據了水面...',
        desc: '來自南美洲，觀賞植物，佔據了水面，阻擋水上交通，遮擋了陽光，使水中生物死亡',
    },
    {
        no: '07',
        name: '互花米草',
        img: 'plants/img/IMG_NO07.png',
        type: '草本植物',
        genus: '禾本科鼠尾粟屬',
        title: '來自大海的另一端 沿海生態的入侵者...',
        desc: '來自北美洲，擁有強韌的生命力，會改變濕地的環境，破換原生種的棲地',
    },
    {
        no: '08',
        name: '馬纓丹',
        img: 'plants/img/IMG_NO08.png',
        type: '草本植物',
        genus: '馬鞭草科馬纓丹屬',
        title: '越是艷麗 越是危險 警告著所有人...',
        desc: '來自美洲，觀賞植物，適應台灣氣候，莖葉與果實有毒，會排斥其他植物',
    },
    {
        no: '09',
        name: '紫花藿香薊',
        img: 'plants/img/IMG_NO09.png',
        type: '草本植物',
        genus: '菊科藿香薊屬',
        title: '看似浪漫的花 卻是無形的壓迫...',
        desc: '來自熱帶美洲，繁殖力強，散發特的香氣，會產生抑制植物生長的物質',
    },
    {
        no: '10',
        name: '貓腥草',
        img: 'plants/img/IMG_NO10.png',
        type: '草本植物',
        genus: '菊科澤蘭屬',
        title: '死亡的氣息 靜靜地在一隅生長...',
        desc: '來自南美洲，散發有毒惡臭，降低食慾，誤食對牲畜及人體有毒',
    },
    {
        no: '11',
        name: '豬草',
        img: 'plants/img/IMG_NO11.png',
        type: '草本植物',
        genus: '菊科豬草屬',
        title: '每逢九月 百萬的花粉 是人們的噩夢...',
        desc: '來自北美洲，繁殖力強，能產生數以百萬的花粉，如黃霧般，使人產生不適',
    },
    {
        no: '12',
        name: '美洲含羞草',
        img: 'plants/img/IMG_NO12.png',
        type: '藤本植物',
        genus: '豆科含羞草屬',
        title: '身上的刺絕不是裝飾 是生存的防禦...',
        desc: '來自熱帶美洲，繁殖力強，散發特的香氣，會產生抑制植物生長的物質',
    },
    {
        no: '13',
        name: '銀膠菊',
        img: 'plants/img/IMG_NO13.png',
        type: '草本植物',
        genus: '菊科銀膠菊屬',
        title: '如同滿天星的白花 碰到就會引起不適...',
        desc: '來自南美洲，全身有毒，有抑制其他植物的成分，會引起人體過敏性反應',
    },
    {
        no: '14',
        name: '銀合歡',
        img: 'plants/img/IMG_NO14.png',
        type: '灌木',
        genus: '豆科銀合歡屬',
        title: '弱者只有死亡一途...',
        desc: '來自美洲，幼葉及莢果對人體有毒性，有強烈的排他性，抑制其他植物生長',
    },
    {
        no: '15',
        name: '日本菟絲子',
        img: 'plants/img/IMG_NO15.png',
        type: '寄生植物',
        genus: '旋花科菟絲子屬',
        title: '吸血的不死怪物 即使斷肢也能重生...',
        desc: '寄生在其他植物身上，吸取他們的養分，即使斷肢也能重生',
    },
]

export default PLANTS
